import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Banner from '../components/Banner/Banner'
import Navbar from '../components/Navbar/Navbar'
import SectionCards from '@/components/Card/SectionCards'
import {getVideos} from "@/lib/Videos"
export default function Home() {
  const movies = getVideos()
  return (
    <>
      <Head>
        <title>Netflix Clone Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.container}>
        <div className={styles.description}>
          <Navbar userName="hadeersalah@gmail.com"/>
          <Banner title="clifford the red dog" subTitle="a redish dog" imgUrl="/public/static/clifford.webp"/>
          <div className={styles.sectionWrapper}>
            <SectionCards title="Movies & Series" videos = {movies} size="large"/>
            <SectionCards title="Movies & Series" videos = {movies} size="medium"/>

          </div>
          

        </div>
      </main>
    </>
  )
}
